name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: "$RESOLVED_VERSION"
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending

categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking-change"
  - title: "✨ New features"
    labels:
      - "new-feature"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
  - title: "⬆️ Dependency updates"
    collapse-after: 5
    labels:
      - "dependency-update"


include-labels:
  - "bugfix"
  - "new-feature"
  - "breaking-change"

no-changes-template: '- No changes'

template: |
  ## What's Changed

  $CHANGES

  [Releases](https://github.com/ApolloAutomation/PLT-1/releases)